// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(sessionID) {
    return $Call.ByID(3245855500, sessionID);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ChatSession | null>}
 */
export function GetSession(sessionID) {
    return $Call.ByID(3954836575, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SessionInfo[]>}
 */
export function GetSessions() {
    return $Call.ByID(1104449860).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TokenUsage>}
 */
export function GetTokenUsage() {
    return $Call.ByID(2283393733).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ChatSession | null>}
 */
export function NewSession() {
    return $Call.ByID(787229693).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SendMessageRequest} req
 * @returns {$CancellablePromise<$models.SendMessageResponse>}
 */
export function SendMessage(req) {
    return $Call.ByID(1063940756, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ChatSession.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.SessionInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.TokenUsage.createFrom;
const $$createType5 = $models.SendMessageResponse.createFrom;
