// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class ChatSession {
    /**
     * Creates a new ChatSession instance.
     * @param {Partial<ChatSession>} [$$source = {}] - The source object to create the ChatSession.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {Message[]}
             */
            this["messages"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatSession}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        return new ChatSession(/** @type {Partial<ChatSession>} */($$parsedSource));
    }
}

export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {Role}
             */
            this["role"] = Role.$zero;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["time"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Role = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RoleUser: "user",
    RoleAssistant: "assistant",
};

export class SendMessageRequest {
    /**
     * Creates a new SendMessageRequest instance.
     * @param {Partial<SendMessageRequest>} [$$source = {}] - The source object to create the SendMessageRequest.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendMessageRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendMessageRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendMessageRequest(/** @type {Partial<SendMessageRequest>} */($$parsedSource));
    }
}

export class SendMessageResponse {
    /**
     * Creates a new SendMessageResponse instance.
     * @param {Partial<SendMessageResponse>} [$$source = {}] - The source object to create the SendMessageResponse.
     */
    constructor($$source = {}) {
        if (!("userMessage" in $$source)) {
            /**
             * @member
             * @type {Message}
             */
            this["userMessage"] = (new Message());
        }
        if (!("assistantMessage" in $$source)) {
            /**
             * @member
             * @type {Message}
             */
            this["assistantMessage"] = (new Message());
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("tokenUsage" in $$source)) {
            /**
             * @member
             * @type {TokenUsage}
             */
            this["tokenUsage"] = (new TokenUsage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendMessageResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendMessageResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("userMessage" in $$parsedSource) {
            $$parsedSource["userMessage"] = $$createField0_0($$parsedSource["userMessage"]);
        }
        if ("assistantMessage" in $$parsedSource) {
            $$parsedSource["assistantMessage"] = $$createField1_0($$parsedSource["assistantMessage"]);
        }
        if ("tokenUsage" in $$parsedSource) {
            $$parsedSource["tokenUsage"] = $$createField3_0($$parsedSource["tokenUsage"]);
        }
        return new SendMessageResponse(/** @type {Partial<SendMessageResponse>} */($$parsedSource));
    }
}

export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("msgCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["msgCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

export class TokenUsage {
    /**
     * Creates a new TokenUsage instance.
     * @param {Partial<TokenUsage>} [$$source = {}] - The source object to create the TokenUsage.
     */
    constructor($$source = {}) {
        if (!("sessionTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TokenUsage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenUsage(/** @type {Partial<TokenUsage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TokenUsage.createFrom;
